version: "3"

services:

  weather-map:
    image: ntt-data/weather-map
    container_name: weather-map
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
      context: weather-map
    expose:
        - "8100"
    ports:
        - "8100:8100"
    environment:
      - WEATHER_STATION_CLIENT_API_MP_REST_URL=http://weather-station:8200

  weather-station:
    image: ntt-data/weather-station
    depends_on:
      - database
    container_name: weather-station
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
      context: weather-station
    expose:
        - "8200"
    ports:
        - "8200:8200"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=dbuser
      - QUARKUS_DATASOURCE_PASSWORD=dbpassword
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/weather

  database:
    container_name: database
    image: postgres:11
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=weather
    ports:
      - 5432:5432
